# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      #Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      #Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      #Logowanie do Dockerhuba
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
          
      #Zbudowanie i wypchniecie obrazu na dockhuba
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          platforms: linux/amd64,linux/s390,linux/arm64
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            gmanos/zadanie1:z1githubactions
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
